[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[scripts]
test = "npx mocha tests/cardinal.test.js --timeout 60000"

[programs.localnet]
solana_nft_programs_token_manager = "9rRm9jSDyPhqkmpcn8oFBfrR46jQwRPacRknj1i9Pge6"
solana_nft_programs_paid_claim_approver = "BcpUG33Z6S3sDbT1YGXmYgE8D2VQ1i2x8yZMzA3yXtFx"
solana_nft_programs_time_invalidator = "7hAFqUxwnJtwEiMX39HaVQ8brLguVVf359Q45oWcqfK6"
solana_nft_programs_use_invalidator = "6bmp1HxmVbEJipcFLkHvkwezRZBowUzB21FwcACkkfdd"
solana_nft_programs_transfer_authority = "Hu7p8c6X5YBUHMezw5ANBVhLD1P86ELioKNbXLNhSsTT"

[test.validator]
startup_wait = 10000
